# -*- coding: utf-8 -*-
"""PROJECT SEM.PR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTkn8v-nB66B6adZHfv4skkdBbUKN7Sn
"""

! curl -fsSL https://ollama.com./install.sh | sh

import subprocess
process = subprocess.Popen ("ollama serve", shell=True)

!ollama pull llama3

!ollama run llama3

!pip install ollama wn

!pip install wn

import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

prompt = 'What does the word *dog* mean'
from ollama import chat, ChatResponse, generate
result = generate(model='llama3',prompt=prompt)
response = result['response']
print(response)

import wn

word = "log"
wn.download('oewn')

ewn = wn.Wordnet('oewn:2024')

import json
sentence = 'I entered it in the log.'
def make_prompt(lemma, sentence):
  sss = ewn.synsets(lemma)
  meanings = dict()
  for ss in sss:
    meanings[ss.id] = ss.definition()
  prompt = f"""
  Which of the following meanings of *{lemma}* is correct in this sentence:
  *{sentence}*?

  {json.dumps(meanings)}

  Return just the key"""
  return prompt

prompt = make_prompt(word, sentence)
print(prompt)

result = generate(model='llama3',prompt=prompt)
response = result['response']
print(response)

!ollama pull qwen3

result = generate(model='qwen3',prompt=prompt)
response = result['response']
print(response)
